# Generated by Django 5.1.6 on 2025-03-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID', db_index = True)),
                ('all_price', models.DecimalField(db_default=0, decimal_places=2, default=0, max_digits=10)),
                ('items', models.ManyToManyField(to='items.items')),
            ],
            options={
                'db_table': 'orders',
                'db_table_comment': 'Table for orders',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='idx_order_pk')],
            },
        ),
    ]
